// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4K4dGNFSFsnw1k6Zxs5LVmi6zY4DaT4o',
    appId: '1:50771981461:web:881a44a94742782460579c',
    messagingSenderId: '50771981461',
    projectId: 'city-guide-c378d',
    authDomain: 'city-guide-c378d.firebaseapp.com',
    storageBucket: 'city-guide-c378d.firebasestorage.app',
    measurementId: 'G-J67GL1X44P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdrzk0NMbHPwyMGyg8Yf55A8WSFeEhIsw',
    appId: '1:50771981461:android:765d4401717df54360579c',
    messagingSenderId: '50771981461',
    projectId: 'city-guide-c378d',
    storageBucket: 'city-guide-c378d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjMc8dCeb-O1zuixii77PgF56M6PlVciM',
    appId: '1:50771981461:ios:41a390050971d46060579c',
    messagingSenderId: '50771981461',
    projectId: 'city-guide-c378d',
    storageBucket: 'city-guide-c378d.firebasestorage.app',
    iosBundleId: 'com.example.cityGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjMc8dCeb-O1zuixii77PgF56M6PlVciM',
    appId: '1:50771981461:ios:41a390050971d46060579c',
    messagingSenderId: '50771981461',
    projectId: 'city-guide-c378d',
    storageBucket: 'city-guide-c378d.firebasestorage.app',
    iosBundleId: 'com.example.cityGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4K4dGNFSFsnw1k6Zxs5LVmi6zY4DaT4o',
    appId: '1:50771981461:web:698a84e58053226b60579c',
    messagingSenderId: '50771981461',
    projectId: 'city-guide-c378d',
    authDomain: 'city-guide-c378d.firebaseapp.com',
    storageBucket: 'city-guide-c378d.firebasestorage.app',
    measurementId: 'G-J3HN38QNZS',
  );
}
